import {Broadcast} from '../types';

let broadcasts: Broadcast[] = [
  {
    id: Math.random(),
    time: "10:40",
    label: "Broncos (W)",
    desc: "Titans (W)",
    league: "Australian NRL Premiership (W)",
    price: 19,
},
{
    id: Math.random(),
    time: "13:00",
    label: "Australia (W)",
    desc: "Nigeria (W)",
    league: "FIFA World Cup (W)",
    price: 19,
},
{
    id: Math.random(),
    time: "15:40",
    label: "England",
    desc: "Australia",
    league: "The Ashes",
    price: 19,
},
{
    id: Math.random(),
    time: "16:00",
    label: "West Indies",
    desc: "India",
    league: "One Day Internationals",
    price: 19,
},
{
    id: Math.random(),
    time: "20:10",
    label: "Detroit Tigers",
    desc: "Los Angeles Angels",
    price: 19,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Huddersfield Giants",
    desc: "Hull FC",
    league: "English Super League",
    price: 19,
},
{
    id: Math.random(),
    time: "00:05",
    label: "Arizona Diamondbacks",
    desc: "Philadelphia Phillies",
    league: "Major League Baseball",
    price: 20,
},
{
    id: Math.random(),
    time: "02:05",
    label: "Florida Panthers",
    desc: "Toronto Maple Leafs",
    league: "NHL",
    price: 20,
},
{
    id: Math.random(),
    time: "02:05",
    label: "Tampa Bay Lightning",
    desc: "Vancouver Canucks",
    league: "NHL",
    price: 20,
},
{
    id: Math.random(),
    time: "03:03",
    label: "Texas Rangers",
    desc: "Houston Astros",
    league: "Major League Baseball",
    price: 20,
},
{
    id: Math.random(),
    time: "03:15",
    label: "New Orleans Saints",
    desc: "Jacksonville Jaguars",
    league: "NFL",
    price: 20,
},
{
    id: Math.random(),
    time: "04:00",
    label: "Brendan Evans/Cameron Norrie",
    desc: "Leylah Fernandez",
    league: "Nanchang",
    price: 20,
},
{
    id: Math.random(),
    time: "05:35",
    label: "San Jose Sharks",
    desc: "Boston Bruins",
    league: "NHL",
    price: 20,
},
{
    id: Math.random(),
    time: "09:00",
    label: "Adelaide Utd (W)",
    desc: "Central Coast (W)",
    league: "Australian W-League",
    price: 20,
},
{
    id: Math.random(),
    time: "11:30",
    label: "Australia",
    desc: "Pakistan",
    league: "ICC World Cup",
    price: 20,
},
{
    id: Math.random(),
    time: "11:45",
    label: "Hawthorn Hawks (W)",
    desc: "Richmond Tigers (W)",
    league: "AFLW",
    price: 20,
},
{
    id: Math.random(),
    time: "11:45",
    label: "Adelaide United",
    desc: "Central Coast",
    league: "Australian A-League",
    price: 20,
},
{
    id: Math.random(),
    time: "15:00",
    label: "TBC",
    desc: "TBC",
    league: "European Cricket Championship",
    price: 20,
},
{
    id: Math.random(),
    time: "18:00",
    label: "TBC",
    desc: "TBC",
    league: "European Cricket Championship",
    price: 20,
},
{
    id: Math.random(),
    time: "18:00",
    label: "Simba",
    desc: "Al Ahly",
    league: "African Football League",
    price: 20,
},
{
    id: Math.random(),
    time: "21:30",
    label: "Borussia Dortmund",
    desc: "W Bremen",
    league: "German Bundesleague",
    price: 20,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Airdrieonians F.C.",
    desc: "Queens Park",
    league: "Scottish Championship",
    price: 20,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Cliftonville",
    desc: "Linfield",
    league: "Northern Irish Premier League",
    price: 20,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Sheffield Sharks",
    desc: "London Lions",
    league: "British Basketball League (M)",
    price: 20,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Rotherham",
    desc: "Ipswich",
    league: "English Championship",
    price: 20,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Argentina",
    desc: "New Zealand",
    league: "Rugby World Cup 2023",
    price: 20,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Le Havre",
    desc: "Lens",
    league: "French Ligue 1",
    price: 20,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Osasuna",
    desc: "Granada",
    league: "Spanish La league",
    price: 20,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Espanyol",
    desc: "Leganes",
    league: "Spanish Segunda DivisiГіn",
    price: 20,
},
{
    id: Math.random(),
    time: "00:05",
    label: "Texas Rangers",
    desc: "Houston Astros",
    league: "Major League Baseball",
    price: 21,
},
{
    id: Math.random(),
    time: "02:05",
    label: "Columbus Blue Jackets",
    desc: "Calgary Flames",
    league: "NHL",
    price: 21,
},
{
    id: Math.random(),
    time: "02:35",
    label: "New York Islanders",
    desc: "New Jersey Devils",
    league: "NHL",
    price: 21,
},
{
    id: Math.random(),
    time: "03:05",
    label: "Arizona Diamondbacks",
    desc: "Philadelphia Phillies",
    league: "Major League Baseball",
    price: 21,
},
{
    id: Math.random(),
    time: "04:05",
    label: "Taranaki",
    desc: "Hawke's Bay",
    league: "New Zealand Mitre 10 Cup",
    price: 21,
},
{
    id: Math.random(),
    time: "05:45",
    label: "New Zealand (W)",
    desc: "Tonga (W)",
    league: "Pacific Championships",
    price: 21,
},
{
    id: Math.random(),
    time: "06:45",
    label: "Melbourne City (W)",
    desc: "Canberra Utd (W)",
    league: "Australian W-League",
    price: 21,
},
{
    id: Math.random(),
    time: "07:30",
    label: "Macarthur FC",
    desc: "Brisbane Roar",
    league: "Australian A-League",
    price: 21,
},
{
    id: Math.random(),
    time: "08:00",
    label: "Netherlands",
    desc: "Sri Lanka",
    league: "ICC World Cup",
    price: 21,
},
{
    id: Math.random(),
    time: "09:30",
    label: "Melbourne City",
    desc: "Western Utd",
    league: "Australian A-League",
    price: 21,
},
{
    id: Math.random(),
    time: "11:15",
    label: "Melbourne (W)",
    desc: "North Melbourne Kangaroos (W)",
    league: "AFLW",
    price: 21,
},
{
    id: Math.random(),
    time: "11:30",
    label: "England",
    desc: "South Africa",
    league: "ICC World Cup",
    price: 21,
},
{
    id: Math.random(),
    time: "11:45",
    label: "Sydney FC",
    desc: "Melbourne Victory",
    league: "Australian A-League",
    price: 21,
},
{
    id: Math.random(),
    time: "14:30",
    label: "Liverpool",
    desc: "Everton",
    league: "Premier League",
    price: 21,
},
{
    id: Math.random(),
    time: "14:30",
    label: "Preston",
    desc: "Millwall",
    league: "English Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "14:30",
    label: "Aston Villa (W)",
    desc: "Tottenham (W)",
    league: "English Women's Super League",
    price: 21,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Sociedad",
    desc: "Mallorca",
    league: "Spanish La league",
    price: 21,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Zebre",
    desc: "Ulster",
    league: "United Rugby Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "17:00",
    label: "Connacht",
    desc: "Ospreys",
    league: "United Rugby Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "17:00",
    label: "Norwich",
    desc: "Leeds",
    league: "English Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "17:05",
    label: "Leicester Tigers",
    desc: "Sale Sharks",
    league: "Premiership Rugby",
    price: 21,
},
{
    id: Math.random(),
    time: "17:05",
    label: "Newport Gwent Dragons",
    desc: "Edinburgh",
    league: "United Rugby Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "17:15",
    label: "Getafe",
    desc: "Betis",
    league: "Spanish La league",
    price: 21,
},
{
    id: Math.random(),
    time: "17:15",
    label: "Villarreal B",
    desc: "Mirandes",
    league: "Spanish Segunda DivisiГіn",
    price: 21,
},
{
    id: Math.random(),
    time: "17:15",
    label: "Amorebieta",
    desc: "Real Oviedo",
    league: "Spanish Segunda DivisiГіn",
    price: 21,
},
{
    id: Math.random(),
    time: "19:00",
    label: "Torino",
    desc: "Inter",
    league: "Italian Serie A",
    price: 21,
},
{
    id: Math.random(),
    time: "19:15",
    label: "Leicester (W)",
    desc: "Man City (W)",
    league: "English Women's Super League",
    price: 21,
},
{
    id: Math.random(),
    time: "19:15",
    label: "Munster",
    desc: "Sharks",
    league: "United Rugby Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "19:15",
    label: "Cardiff Blues",
    desc: "Benetton Treviso",
    league: "United Rugby Championship",
    price: 21,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Mainz",
    desc: "Bayern Munich",
    league: "German Bundesleague",
    price: 21,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Chelsea",
    desc: "Arsenal",
    league: "Premier League",
    price: 21,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Wealdstone",
    desc: "Boreham Wood",
    league: "English National League",
    price: 21,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Sevilla FC",
    desc: "Real Madrid",
    league: "Spanish La league",
    price: 21,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Tenerife",
    desc: "Levante",
    league: "Spanish Segunda DivisiГіn",
    price: 21,
},
{
    id: Math.random(),
    time: "21:00",
    label: "Makhachev",
    desc: "Volkanovski 2",
    league: "UFC",
    price: 21,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Sassuolo",
    desc: "Lazio",
    league: "Italian Serie A",
    price: 21,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Sheffield Utd",
    desc: "Man Utd",
    league: "Premier League",
    price: 21,
},
{
    id: Math.random(),
    time: "22:00",
    label: "England",
    desc: "South Africa",
    league: "Rugby World Cup 2023",
    price: 21,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Nice",
    desc: "Marseille",
    league: "French Ligue 1",
    price: 21,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Celta Vigo",
    desc: "Atl Madrid",
    league: "Spanish La league",
    price: 21,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Zaragoza",
    desc: "Eibar",
    league: "Spanish Segunda DivisiГіn",
    price: 21,
},
{
    id: Math.random(),
    time: "00:00",
    label: "Jack Catterall",
    desc: "Jorge Linares",
    league: "Boxing",
    price: 22,
},
{
    id: Math.random(),
    time: "02:05",
    label: "Montreal Canadiens",
    desc: "Washington Capitals",
    league: "NHL",
    price: 22,
},
{
    id: Math.random(),
    time: "03:05",
    label: "Arizona Diamondbacks",
    desc: "Philadelphia Phillies",
    league: "Major League Baseball",
    price: 22,
},
{
    id: Math.random(),
    time: "05:00",
    label: "Alexis Rocha",
    desc: "Giovani Santillan",
    league: "Boxing",
    price: 22,
},
{
    id: Math.random(),
    time: "05:05",
    label: "Seattle Kraken",
    desc: "New York Rangers",
    league: "NHL",
    price: 22,
},
{
    id: Math.random(),
    time: "05:40",
    label: "Perth Scorchers (W)",
    desc: "Brisbane Heat (W)",
    league: "Big Bash League (W)",
    price: 22,
},
{
    id: Math.random(),
    time: "07:00",
    label: "West Sydney Wanderers",
    desc: "Wellington Phoenix",
    league: "Australian A-League",
    price: 22,
},
{
    id: Math.random(),
    time: "08:00",
    label: "Fiji",
    desc: "Cook Islands",
    league: "Pacific Championships",
    price: 22,
},
{
    id: Math.random(),
    time: "11:30",
    label: "India",
    desc: "New Zealand",
    league: "ICC World Cup",
    price: 22,
},
{
    id: Math.random(),
    time: "11:45",
    label: "Perth Glory",
    desc: "Newcastle Jets",
    league: "Australian A-League",
    price: 22,
},
{
    id: Math.random(),
    time: "13:30",
    label: "Roma",
    desc: "Monza",
    league: "Italian Serie A",
    price: 22,
},
{
    id: Math.random(),
    time: "14:00",
    label: "Lorient",
    desc: "Rennes",
    league: "French Ligue 1",
    price: 22,
},
{
    id: Math.random(),
    time: "14:00",
    label: "Celtic (W)",
    desc: "Rangers (W)",
    league: "Scottish Women's Premier League",
    price: 22,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Las Palmas",
    desc: "Rayo Vallecano",
    league: "Spanish La league",
    price: 22,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Everton (W)",
    desc: "Man Utd (W)",
    league: "English Women's Super League",
    price: 22,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Ferrol",
    desc: "Eldense",
    league: "Spanish Segunda DivisiГіn",
    price: 22,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Bologna",
    desc: "Frosinone",
    league: "Italian Serie A",
    price: 22,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Salernitana",
    desc: "Cagliari",
    league: "Italian Serie A",
    price: 22,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Lille",
    desc: "Brest",
    league: "French Ligue 1",
    price: 22,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Chelsea (W)",
    desc: "Brighton (W)",
    league: "English Women's Super League",
    price: 22,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Bulls",
    desc: "Scarlets",
    league: "United Rugby Championship",
    price: 22,
},
{
    id: Math.random(),
    time: "16:15",
    label: "Hearts",
    desc: "Celtic",
    league: "Scottish Premiership",
    price: 22,
},
{
    id: Math.random(),
    time: "16:30",
    label: "FC Koln",
    desc: "Mgladbach",
    league: "German Bundesleague",
    price: 22,
},
{
    id: Math.random(),
    time: "16:30",
    label: "England",
    desc: "Tonga",
    league: "Internationals",
    price: 22,
},
{
    id: Math.random(),
    time: "17:00",
    label: "Harlequins",
    desc: "Exeter Chiefs",
    league: "Premiership Rugby",
    price: 22,
},
{
    id: Math.random(),
    time: "17:00",
    label: "Hearts (W)",
    desc: "Motherwell (W)",
    league: "Scottish Women's Premier League",
    price: 22,
},
{
    id: Math.random(),
    time: "17:15",
    label: "Girona",
    desc: "Almeria",
    league: "Spanish La league",
    price: 22,
},
{
    id: Math.random(),
    time: "17:15",
    label: "Huesca",
    desc: "Elche",
    league: "Spanish Segunda DivisiГіn",
    price: 22,
},
{
    id: Math.random(),
    time: "18:00",
    label: "Glasgow Warriors",
    desc: "Leinster",
    league: "United Rugby Championship",
    price: 22,
},
{
    id: Math.random(),
    time: "18:05",
    label: "Monaco",
    desc: "Metz",
    league: "French Ligue 1",
    price: 22,
},
{
    id: Math.random(),
    time: "18:30",
    label: "FC Heidenheim",
    desc: "Augsburg",
    league: "German Bundesleague",
    price: 22,
},
{
    id: Math.random(),
    time: "18:30",
    label: "Aston Villa",
    desc: "West Ham",
    league: "Premier League",
    price: 22,
},
{
    id: Math.random(),
    time: "19:00",
    label: "Atalanta",
    desc: "Genoa",
    league: "Italian Serie A",
    price: 22,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Villarreal",
    desc: "Alaves",
    league: "Spanish La league",
    price: 22,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Santander",
    desc: "Burgos",
    league: "Spanish Segunda DivisiГіn",
    price: 22,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Albacete",
    desc: "Gijon",
    league: "Spanish Segunda DivisiГіn",
    price: 22,
},
{
    id: Math.random(),
    time: "20:00", label: "TBC", desc: "TBC", league: "NFL", price: 22
},
{
    id: Math.random(),
    time: "20:00",
    label: "Indianapolis Colts",
    desc: "Cleveland Browns",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "20:00",
    label: "Tampa Bay Buccaneers",
    desc: "Atlanta Falcons",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "20:00",
    label: "Baltimore Ravens",
    desc: "Detroit Lions",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "20:00",
    label: "New York Giants",
    desc: "Washington Commanders",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "20:00",
    label: "Chicago Bears",
    desc: "Las Vegas Raiders",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "20:00",
    label: "New England Patriots",
    desc: "Buffalo Bills",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "20:45",
    label: "Bristol City (W)",
    desc: "Arsenal (W)",
    league: "English Women's Super League",
    price: 22,
},
{
    id: Math.random(),
    time: "21:45",
    label: "AC Milan",
    desc: "Juventus",
    league: "Italian Serie A",
    price: 22,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Lyon",
    desc: "Clermont",
    league: "French Ligue 1",
    price: 22,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Barcelona",
    desc: "Ath Bilbao",
    league: "Spanish La league",
    price: 22,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Valladolid",
    desc: "FC Andorra",
    league: "Spanish Segunda DivisiГіn",
    price: 22,
},
{
    id: Math.random(),
    time: "23:05",
    label: "Los Angeles Rams",
    desc: "Pittsburgh Steelers",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "23:05",
    label: "Seattle Seahawks",
    desc: "Arizona Cardinals",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "23:25", label: "TBC", desc: "TBC", league: "NFL", price: 22
},
{
    id: Math.random(),
    time: "23:25",
    label: "Denver Broncos",
    desc: "Green Bay Packers",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "23:25",
    label: "Kansas City Chiefs",
    desc: "Los Angeles Chargers",
    league: "NFL",
    price: 22,
},
{
    id: Math.random(),
    time: "03:03",
    label: "Houston Astros",
    desc: "Texas Rangers",
    league: "Major League Baseball",
    price: 23,
},
{
    id: Math.random(),
    time: "03:20",
    label: "Philadelphia Eagles",
    desc: "Miami Dolphins",
    league: "NFL",
    price: 23,
},
{
    id: Math.random(),
    time: "03:35",
    label: "Anaheim Ducks",
    desc: "Boston Bruins",
    league: "NHL",
    price: 23,
},
{
    id: Math.random(),
    time: "11:30",
    label: "Pakistan",
    desc: "Afghanistan",
    league: "ICC World Cup",
    price: 23,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Udinese",
    desc: "Lecce",
    league: "Italian Serie A",
    price: 23,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Fiorentina",
    desc: "Empoli",
    league: "Italian Serie A",
    price: 23,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Tottenham",
    desc: "Fulham",
    league: "Premier League",
    price: 23,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Valencia",
    desc: "Cadiz",
    league: "Spanish La league",
    price: 23,
},
{
    id: Math.random(),
    time: "03:15",
    label: "Minnesota Vikings",
    desc: "San Francisco 49ers",
    league: "NFL",
    price: 24,
},
{
    id: Math.random(),
    time: "11:30",
    label: "South Africa",
    desc: "Bangladesh",
    league: "ICC World Cup",
    price: 24,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Man Utd U19",
    desc: "FC Copenhagen U19",
    league: "UEFA Youth League",
    price: 24,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Galatasaray",
    desc: "Bayern Munich",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Inter",
    desc: "Red Bull Salzburg",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Swansea",
    desc: "Watford",
    league: "English Championship",
    price: 24,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Huddersfield",
    desc: "Cardiff",
    league: "English Championship",
    price: 24,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Millwall",
    desc: "Blackburn",
    league: "English Championship",
    price: 24,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Norwich",
    desc: "Middlesbrough",
    league: "English Championship",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Sevilla FC",
    desc: "Arsenal",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Man Utd",
    desc: "FC Copenhagen",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Benfica",
    desc: "Sociedad",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Braga",
    desc: "Real Madrid",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Union Berlin",
    desc: "Napoli",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Lens",
    desc: "PSV",
    league: "UEFA Champions League",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Leicester",
    desc: "Sunderland",
    league: "English Championship",
    price: 24,
},
{
    id: Math.random(),
    time: "22:00",
    label: "West Brom",
    desc: "QPR",
    league: "English Championship",
    price: 24,
},
,
{
    id: Math.random(),
    time: "11:30",
    label: "Australia",
    desc: "Netherlands",
    league: "ICC World Cup",
    price: 25,
},
{
    id: Math.random(),
    time: "17:00",
    label: "Newcastle U19",
    desc: "Dortmund U19",
    league: "UEFA Youth League",
    price: 25,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Barcelona",
    desc: "Shakhtar",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Feyenoord",
    desc: "Lazio",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Preston",
    desc: "Southampton",
    league: "English Championship",
    price: 25,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Rotherham",
    desc: "Coventry",
    league: "English Championship",
    price: 25,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Plymouth",
    desc: "Sheffield Wednesday",
    league: "English Championship",
    price: 25,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Bristol City",
    desc: "Ipswich",
    league: "English Championship",
    price: 25,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Birmingham",
    desc: "Hull City",
    league: "English Championship",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Celtic",
    desc: "Atl Madrid",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Paris",
    desc: "AC Milan",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Antwerp",
    desc: "Porto",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Newcastle",
    desc: "Borussia Dortmund",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "RB Leipzig",
    desc: "Crvena Zvezda",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Young Boys",
    desc: "Man City",
    league: "UEFA Champions League",
    price: 25,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Stoke",
    desc: "Leeds",
    league: "English Championship",
    price: 25,
},
{
    id: Math.random(),
    time: "11:30",
    label: "England",
    desc: "Sri Lanka",
    league: "ICC World Cup",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Molde",
    desc: "Hacken",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Sturm Graz",
    desc: "Atalanta",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Aris Limassol",
    desc: "Betis",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Sparta Prague",
    desc: "Rangers",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Marseille",
    desc: "AEK",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "TSC Backa Topola",
    desc: "Freiburg",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Olympiakos",
    desc: "West Ham",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Rakow",
    desc: "Sporting Lisbon",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Fenerbahce",
    desc: "Ludogorets",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Lille",
    desc: "Slovan Bratislava",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "KI Klaksvik",
    desc: "Olimpija",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Gent",
    desc: "Breidablik",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Maccabi Tel Aviv",
    desc: "Zorya",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Lugano",
    desc: "Club Brugge",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "AZ Alkmaar",
    desc: "Aston Villa",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "19:45",
    label: "Ballkani",
    desc: "FC Astana",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Union St Gilloise",
    desc: "LASK Linz",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Liverpool",
    desc: "Toulouse",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Villarreal",
    desc: "Maccabi Haifa",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Panathinaikos",
    desc: "Rennes",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Roma",
    desc: "Slavia Prague",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Leverkusen",
    desc: "Karabakh",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "FC Sheriff",
    desc: "Servette",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Dinamo Zagreb",
    desc: "Plzen",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Fiorentina",
    desc: "Cukaricki",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Aberdeen",
    desc: "PAOK",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Zrinjski Mostar",
    desc: "Legia Warsaw",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Genk",
    desc: "Ferencvaros",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Eintracht Frankfurt",
    desc: "HJK Helsinki",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Spartak Trnava",
    desc: "FC Nordsjaelland",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Bodo/Glimt",
    desc: "Besiktas",
    league: "Europa Conference League",
    price: 26,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Brighton",
    desc: "Ajax",
    league: "UEFA Europa League",
    price: 26,
},
{
    id: Math.random(),
    time: "03:15",
    label: "Buffalo Bills",
    desc: "Tampa Bay Buccaneers",
    league: "NFL",
    price: 27,
},
{
    id: Math.random(),
    time: "11:30",
    label: "Pakistan",
    desc: "South Africa",
    league: "ICC World Cup",
    price: 27,
},
{
    id: Math.random(),
    time: "11:45",
    label: "Gold Coast Suns (W)",
    desc: "GWS Giants (W)",
    league: "AFLW",
    price: 27,
},
{
    id: Math.random(),
    time: "12:30",
    label: "Brisbane Heat (W)",
    desc: "Melbourne Stars (W)",
    league: "Big Bash League (W)",
    price: 27,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Genoa",
    desc: "Salernitana",
    league: "Italian Serie A",
    price: 27,
},
{
    id: Math.random(),
    time: "21:45",
    label: "England (W)",
    desc: "Belgium (W)",
    league: "UEFA Women's Nations League",
    price: 27,
},
{
    id: Math.random(),
    time: "21:45",
    label: "Netherlands (W)",
    desc: "Scotland (W)",
    league: "UEFA Women's Nations League",
    price: 27,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Crystal Palace",
    desc: "Tottenham",
    league: "Premier League",
    price: 27,
},
{
    id: Math.random(),
    time: "22:00",
    label: "TBC",
    desc: "TBC",
    league: "Rugby World Cup 2023",
    price: 27,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Girona",
    desc: "Celta Vigo",
    league: "Spanish La league",
    price: 27,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Clermont",
    desc: "Nice",
    league: "French Ligue 1",
    price: 27,
},
{
    id: Math.random(),
    time: "05:00",
    label: "Amanda Serrano",
    desc: "Danila Ramos",
    league: "Boxing",
    price: 28,
},
{
    id: Math.random(),
    time: "08:00",
    label: "Australia",
    desc: "New Zealand",
    league: "ICC World Cup",
    price: 28,
},
{
    id: Math.random(),
    time: "10:00",
    label: "Australia (W)",
    desc: "New Zealand (W)",
    league: "Pacific Championships",
    price: 28,
},
{
    id: Math.random(),
    time: "11:30",
    label: "Netherlands",
    desc: "Bangladesh",
    league: "ICC World Cup",
    price: 28,
},
{
    id: Math.random(),
    time: "14:30",
    label: "Chelsea",
    desc: "Brentford",
    league: "Premier League",
    price: 28,
},
{
    id: Math.random(),
    time: "14:30",
    label: "Southampton",
    desc: "Birmingham",
    league: "English Championship",
    price: 28,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Almeria",
    desc: "Las Palmas",
    league: "Spanish La league",
    price: 28,
},
{
    id: Math.random(),
    time: "16:30",
    label: "Bristol Bears",
    desc: "Harlequins",
    league: "Premiership Rugby",
    price: 28,
},
{
    id: Math.random(),
    time: "17:15",
    label: "Barcelona",
    desc: "Real Madrid",
    league: "Spanish La league",
    price: 28,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Wolves",
    desc: "Newcastle",
    league: "Premier League",
    price: 28,
},
{
    id: Math.random(),
    time: "19:30",
    label: "York City",
    desc: "FC Halifax Town",
    league: "English National League",
    price: 28,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Montrose",
    desc: "Hamilton",
    league: "Scottish Division 2",
    price: 28,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Newry",
    desc: "Larne",
    league: "Northern Irish Premier League",
    price: 28,
},
{
    id: Math.random(),
    time: "19:30",
    label: "Mallorca",
    desc: "Getafe",
    league: "Spanish La league",
    price: 28,
},
{
    id: Math.random(),
    time: "22:00",
    label: "TBC",
    desc: "TBC",
    league: "Rugby World Cup 2023",
    price: 28,
},
{
    id: Math.random(),
    time: "22:00",
    label: "Cadiz",
    desc: "Sevilla FC",
    league: "Spanish La league",
    price: 28,
},
{
    id: Math.random(),
    time: "00:00",
    label: "Tyson Fury",
    desc: "Francis Ngannou",
    league: "Boxing",
    price: 29,
},
{
    id: Math.random(),
    time: "06:00",
    label: "Shaquie Foster",
    desc: "Eduardo Hernandez",
    league: "Boxing",
    price: 29,
},
{
    id: Math.random(),
    time: "11:30",
    label: "India",
    desc: "England",
    league: "ICC World Cup",
    price: 29,
},
{
    id: Math.random(),
    time: "15:00",
    label: "Kilmarnock",
    desc: "Aberdeen",
    league: "Scottish Premiership",
    price: 29,
},
{
    id: Math.random(),
    time: "16:00",
    label: "West Ham",
    desc: "Everton",
    league: "Premier League",
    price: 29,
},
{
    id: Math.random(),
    time: "16:00",
    label: "Betis",
    desc: "Osasuna",
    league: "Spanish La league",
    price: 29,
},
{
    id: Math.random(),
    time: "18:00",
    label: "Newcastle Falcons",
    desc: "Northampton Saints",
    league: "Premiership Rugby",
    price: 29,
},
{
    id: Math.random(),
    time: "18:15",
    label: "Rayo Vallecano",
    desc: "Sociedad",
    league: "Spanish La league",
    price: 29,
},
{
    id: Math.random(),
    time: "18:30",
    label: "Man Utd",
    desc: "Man City",
    league: "Premier League",
    price: 29,
},
{
    id: Math.random(),
    time: "20:00",
    label: "Pittsburgh Steelers",
    desc: "Jacksonville Jaguars",
    league: "NFL",
    price: 29,
},
{
    id: Math.random(),
    time: "20:00",
    label: "Dallas Cowboys",
    desc: "Los Angeles Rams",
    league: "NFL",
    price: 29,
},
{
    id: Math.random(),
    time: "20:30",
    label: "Ath Bilbao",
    desc: "Valencia",
    league: "Spanish La league",
    price: 29,
},
{
    id: Math.random(),
    time: "21:00", label: "TBC", desc: "TBC", league: "NFL", price: 29
},
{
    id: Math.random(),
    time: "23:00",
    label: "Atl Madrid",
    desc: "Alaves",
    league: "Spanish La league",
    price: 29,
},
{
    id: Math.random(),
    time: "00:25", label: "TBC", desc: "TBC", league: "NFL", price: 30
},
{
    id: Math.random(),
    time: "11:30",
    label: "Afghanistan",
    desc: "Sri Lanka",
    league: "ICC World Cup",
    price: 30,
},
{
    id: Math.random(),
    time: "22:45",
    label: "Musselburgh Ath",
    desc: "Clyde",
    league: "Scottish FA Cup",
    price: 30,
},
{
    id: Math.random(),
    time: "23:00",
    label: "Coventry",
    desc: "West Brom",
    league: "English Championship",
    price: 30,
},
{
    id: Math.random(),
    time: "23:00",
    label: "Granada",
    desc: "Villarreal",
    league: "Spanish La league",
    price: 30,
},
{
    id: Math.random(),
    time: "11:30",
    label: "Pakistan",
    desc: "Bangladesh",
    league: "ICC World Cup",
    price: 31,
},
{
    id: Math.random(),
    time: "22:30",
    label: "Belgium (W)",
    desc: "England (W)",
    league: "UEFA Women's Nations League",
    price: 31,
},
];


broadcasts = broadcasts.filter(el => el.price >= new Date().getDate())

export {broadcasts};